### ISSUE TITLE
Problem with make command

### ISSUE THREAD

**Issue by kichyr** [layeredqueuing/V5#4]
Hello have problem with make command:
q`
 -MD -MP -MF .deps/liblqio_la-error.Tpo -c error.cpp  -fPIC -DPIC -o .libs/liblqio_la-error.o
error.cpp: In function ‘void LQIO::verrprintf(FILE*, LQIO::error_severity, const char*, unsigned int, unsigned int, const char*, va_list)’:
error.cpp:150:10: error: could not convert ‘args’ from ‘va_list’ {aka ‘__va_lis’} to ‘bool’
  150 |     if ( args ) {
      |          ^~~~
      |          |
      |          va_list {aka __va_list}
`

reproduce on a clean virtual ubuntu 20.04

steps:
sudo apt install build-essential autotools-dev automake libtool flex bison fig2dev libexpat1-dev
git clone https://github.com/SEALABQualityGroup/V5.git
cd V5
autoreconf -vif 
./configure
make
sudo make install

**Comment by layeredqueuing** [comment]
if ( va_list ) is bogus -- there is no way to determine the number of args (including zero) defined officially.

**Comment by layeredqueuing** [comment]
This will be fixed in the next push (later this week) to the V5 repo.  Delete lqiolib/src/error.cpp, line 150 "if ( va_list  ) {" and the "} else { ... }" block.  The dist and V6 repos will be done somewhat later.  It's funny that neither clang nor gcc on my  ubuntu, windows, and fedora machines didn't complain.
